// SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Shared autogenerated sidebar for the migration area plugins (use-data,
// reference, tools, ...). Each plugin loads this independently; pages order by
// the Diataxis `sidebar_position` injected during integration.
const sidebars: SidebarsConfig = {
  areaSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
